### ISSUE TITLE
Replace calling for getSession/getToken with RTK Userstate selector

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#103]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >.
## Description
use VsCode search and look for keywords session or token -- getSession, getToken
## Acception Criteria
- [ ] Actual functionality of feature
- [ ] listed here
- [ ] and another one
## Tasks
- [x] addstudio page getting session for user and role
- [x] addstudioservice page getting session for user and role
- [x] dashboard indexpage
