### ISSUE TITLE
Open Signin/Signup modals via Globalstate and Middleware

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#104]
## Value Proposition
redirect to homepage but with signin param. return in getserversideprops a boolean which in a useeffect dispatches then the openLoginModal state
## Description
// Insert Wire Frame
## Acception Criteria
- [ ] Header Buttons open via globalstate // handleClose closes via globalstate
- [ ] restrictedMiddleware access opens Signin/Signup via globalstate

## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
