### ISSUE TITLE
ScrollSpy for Detailpage

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#112]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >.
## Description
// Insert Wire Frame
## Acception Criteria
- [ ] Actual functionality of feature
- [ ] listed here
- [ ] and another one
## Tasks
- [ ] ScrollSpy from (https://tailwind-elements.com/docs/standard/navigation/scrollspy/) - rightside unter the table without background - plain text - fixed - geos under/behind table at the end of scroll.
