### ISSUE TITLE
Create My Bookings Dashboard-Section for User

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#116]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >.
## Description
Currently there is no Bookingsystem or one to one Chat, but the user can make a booking request by sending an email for right now.
List those requests in this My Bookinsg section with the option to delete it. 
The listing should include all relevant details.

// Insert Wire Frame
## Acception Criteria
- [ ] Every Booking request made by the User will be listed here
## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
