### ISSUE TITLE
Update Next-Auth.js package

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#119]
## Description
Update the package but inside a clone repository to test. 
## Acception Criteria
- [ ] Update package
- [ ] update unstable_getServerSession to only getServerSession
 
## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
