### ISSUE TITLE
Users Profile-Detailpage: Report, Share, Block

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#122]
## Description
Dropdown with following action options: Report, Share, Block -the User.
## Acception Criteria
- [ ] Sharing: Quick sharing options for other plattforms + social card for the User
- [ ] Report: Options for reporting reason. Appers In a dedicated Admin Dashboard area.
- [ ] Block: Block User to User interaction in terms of messaging, booking, reviews and other interaction types
## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
