### ISSUE TITLE
Add User-Login

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#18]
## Value Proposition
As a User who wants to look for studios or as a Hoster who wants to list his studios, I want my own profile so that for example: -my added studios can be uniquely identified as mine, -I can add listings to my favourites.

## Description

![Image](https://user-images.githubusercontent.com/68496958/197496267-ca80b7f9-9bd1-4f6b-b93a-efe16b6be158.png)

## Acception Criteria
- [x] User can register or log-in 
- [x] Add restriction for not logged In Users for create listing page
## Tasks
- [x] add nextauth and bcrypt
- [x] create user model schema
- [x] create nextauth api route in nextauth folder
- [x] add github provider and create auth app in github settings
- [x] setup github provider via its api credentials 
- [x] create custom sign  in page
- [x] add credentials provider logic by adding: find User by email in db, and by matching the password
- [x] create form for login via credentials, into the custom sign in page
- [x] create sign in handler
- [x] create register handler
