### ISSUE TITLE
MongoDB data Fetching

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#27]
## Value Proposition
As a User who is looking for listings, I want to be able to get always  the newest/updated listings so that that no information is missed out or consumed as not up to date .
## Description
The Dummy Data should be fetched from MongoDB and it then should be populating  the listing cards instead of the local fake data.## Acception Criteria
- [x] Fetching data from MongoDB Collection inside SSR function
- [x] populating studio listing card Component with fetched data

## Tasks
- [x] create connection to MongoDB in SSR function
- [x] fetch data
- [x] populate studio listing card component with data
