### ISSUE TITLE
Add Form Functionality

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#3]
## Value Proposition
As a user of the Form, I want to have a user friendly experience and full functionality so that i can use the form as intended(to submit studio details).
## Description
- Add custom opening times checkbox. When clicked, several options show up, to input the opening times from monday-sunday.
![image](https://user-images.githubusercontent.com/68496958/195835516-8e976268-4a71-4d7c-a387-9ffefbf321a1.png)
- Make the Studio type paragraphs clickable, so they can toggle a potentially following state in next user story.
![image](https://user-images.githubusercontent.com/68496958/195835574-209a1d41-a8be-44f0-8f44-fa9ef39c3ed9.png)
- If there will be a sound engineer available (radio button checked) , another field to set the price will show up
##Acception Criteria
- [ ] The form should be fully clickable. All fields/inputs with the intention to be expanded by clicking another input, should work.
- [ ] The form is in a finished state except handling the submition.
## Tasks
- [ ] Conditionally show custom opening time input fields that themself conditionally show-set time fields.
- [ ] Make the studio type paraghap's clickable and conditionally toggle state
- [ ] if one clicks: yes, where he states that he offers a sound engineer, additional fields are conditionally shown(inclusive, on request, and set price fields)
- [ ] Add pacakge for resizing textarea fields automatically.
