### ISSUE TITLE
Prevent/check Document scrolling

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#30]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >.
## Description
If the Searchbar is active, disable scroll. 
_document -> <body> needs to be adjusted for disabling scrolling, if the searchbar is active.
## Acception Criteria
- [x] add to every ClickToClose Overlay to add prevent scrolling on document body
- [x] add to detailpage CalendarOpen Overlay to close calendar on document body is scrolling

## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
