### ISSUE TITLE
handle Form submission to MongoDB

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#32]
## Value Proposition
As a listing Hoster, I want to list my recording studio to the web application by filling out and then submitting the form, so that the typical User can compare my listing with others.

## Description
Handle Form submission in a manner, that the submitted data is accordingly to the listing Schema and is going to be listed in the search results. 
## Acception Criteria
- [x]  Form submission to MongoDB
- [x] Submission on search results page visibility
## Tasks
- [x] create submit handler in forms.js
- [x] create api route for db post request
