### ISSUE TITLE
Design restructure for SignIn page

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#35]
## Value Proposition
As a User and Hoster who wants to sign in or register, to be able to use all functionalities, i want a good user experience

## Description
project restructuring: destructure the form page into components and design the sign in as well as the sign up page to be mobile friendly.

## Acception Criteria
- [x] Form inputs are coming from a component
- [x] Don't show header in signin and signup page
- [x] Signup page
- [x] validation with error messages
## Tasks
- [x] exchange all inputs against FormInput component
- [x] conditionally render _app layout component (if login page = no Header component)
- [x] Split Forminput component
- [x] Copy signin as signup page
- [x] create register route with email validation
- [x] make validation function a component
- [x] depending on return of validation show errormessages
