### ISSUE TITLE
 Bugfix MongoDB User Authentication

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#36]
## Description
A User Table with a email set as empty string inside MongoDB causes the issue, that every email can register and be logged in as "" (empty string).

## Acception Criteria
- [ ] Bugfix
## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
