### ISSUE TITLE
Create Cards, populate with dummyDB

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#4]
## Value Proposition
As a general User[^1], I want to be able to view music studio listings available, with all their services and details, so that I can compare them and contact the best fitting.
## Description
This is a demo of how the Cards, populated with the dummy data should look like. The Check Symbol at the top right's are a dummy for possible "add to favourites" functionality. The list of Cards populated with dummy data will be displayed in a search page
<img width="344" alt="Screenshot 2022-10-17 at 10 56 57" src="https://user-images.githubusercontent.com/68496958/196134876-a01a7d9b-846d-4e82-b095-a1faa095cff4.png">
This is how the dummy data is looking like
<img width="459" alt="Screenshot 2022-10-17 at 11 00 09" src="https://user-images.githubusercontent.com/68496958/196135647-a76831b7-cb74-4249-8ebb-408752183a13.png">
## Acception Criteria
- [x] The listing Cards are populated with most useful data out of the dummy Data
## Tasks
- [x] Set up project structure
- [x] Set up Dummy Data
- [x] Create search page
- [x] Create card component
- [x] Create Card Design along the way populate it with Dummy Data

[^1]: = User who wants to view all Listings and is not a Hoster

**Comment by philmetscher** [comment]
Hey :) Du solltest deine `openingCustom` auch auf Englisch schreiben (momentan `montag`-`freitag` auf Deutsch).
Außerdem sollte ein Preis nicht mit dem Dollar oder Euro Zeichen beschrieben sein in den Daten, sondern nur im Mapping.
Eine Frage zum Entwurf: Was macht das `check-icon` oben bei der card

Hey :) You should write your `openingCustom` also in english (currently `montag`-`freitag` in german).
Also, a price should not be described with the dollar or euro sign in the data (only in the mapping).
One question about the design: What does the `check-icon` do at the top of the card

**Comment by Ozanyurdakul98** [comment]
> Hey :) You should write your `openingCustom` also in english (currently `montag`-`freitag` in german).
> Also, a price should not be described with the dollar or euro sign in the data (only in the mapping).
> One question about the design: What does the `check-icon` do at the top of the card

Hey Phil! Thank you for your input. 
1. I was not sure how to handle proper naming for the input fields and the Objects, considering a potential integration of i18n (localization) some time later. But I've decided to just write everything in one language for now.
2. I have deleted all price tags, thank you for that info.
3. The check Icon is a dummy design aspect, for the intention to set up a "add to favourites" functionality.
