### ISSUE TITLE
Create User roles (admin/host)

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#44]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >.
## Description
// Insert Wire Frame
## Acception Criteria
- [x] on Sign Up user role will be added to account
- [x] Include Account role verification where it is needed (api routes, dashboard admin area)

## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
