### ISSUE TITLE
login / register form upgrade

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#45]
## Value Proposition
As a user I want to stay on the page to be able to login or register

## Acception Criteria
- [ ] restricted pages open signin modal
## Tasks
- [x] make created signin signup components to modals by setting state which triggers popup. Onclicks
- [x] For Headery symbols
- [x] For Usermenu signin and signup, for signup button, for not allowed route accesses.
- [x] add conditional page restrictions to "add listing" and "Account menu"
