### ISSUE TITLE
User Dashboard

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#47]
## Value Proposition
As a User I want to have my own User Dashboard, for better overview of all my controls.

## Acception Criteria
- [x] User Dashboard structure
- [x] Delete Account option
- [x] create listing section
- [x] update user section [picture, name, email, password]
## Tasks
- [x] tasks to achieve the functionalities
- [x] step by step
- [x] to be executed by developer
