### ISSUE TITLE
MongoDB Setup

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#5]
## Value Proposition
As a User who is looking for listings, I want to be able to get always  the newest/updated listings so that that no information is missed out or consumed as not up to date .

## Description
The Dummy Data should be fetched from MongoDB and it then should be populating  the listing cards instead of the local fake data. For this a connection will be build up and the dummy data will be seeded to mongoDB

## Acception Criteria
- [x] Setup MongoDB Connection and seeded Data to MongoDB Collection

## Tasks
- [x] Seed fakeDB data to MongoDB
- [x] create DbConnect file (Next.js boilerplate)

**Comment by F-Kirchhoff** [comment]
Hey Ozan, you are free to add the mongoDB connection early on, but experience shows that it is better to create a basic front end first where you implement the basic CRUD operations. But this is only a suggestion, the user story itself is very good, you found a good value proposition for this very technical user story.

**Comment by Ozanyurdakul98** [comment]
> Hey Ozan, you are free to add the mongoDB connection early on, but experience shows that it is better to create a basic front end first where you implement the basic CRUD operations. But this is only a suggestion, the user story itself is very good, you found a good value proposition for this very technical user story.

Thank you for your Input Felix! 
I'll take that as valuable information so I've decided to push this issue a little more to the future, as you suggest.  So later for the Form submit, etc. all these CRUD operations will be interacting with local dummy DB, as I understood you, this should be appropriate?
For now then, I would just consider to make the SSR part of this task list on the local to DummyDB connections
