### ISSUE TITLE
Bugfix: validation function for createListing is missing checking for empty studioPricing

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#50]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >.
## Description
// Insert Wire Frame
## Acception Criteria
- [x] edit Validate.js to include validation for empty studiopricings for every option
## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
