### ISSUE TITLE
Await calls, Api routes and Spinners

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#52]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >.
## Description
Check all await fetching's if they include/need a loading state and a Spinner. 
## Acception Criteria
- [x] Loading spinner for all await calls, also f.e. edit buttons in Tables
- [x] If Loading then deactivate buttons (Make sure not being able to resubmit after submission and loading end -> by: resetting form, refresh or rederict)

## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
