### ISSUE TITLE
Create category Schema and reference it in Studiolisting schema

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#59]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >.
## Description
// Insert Wire Frame
## Acception Criteria
- [x] Create category schema and reference it in studiolisting schema
- [x] create ssg into landing page to get categories
- [x] in create listing page, categorie options are fetched and mapped
- [x] make studioservice result pages by dynamic routing
- [x] Make studioservice grid section on landingpage
## Tasks
- [ ] tasks to achieve the functionalities
- [ ] step by step
- [ ] to be executed by developer
