### ISSUE TITLE
Create Searchbar & Options

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#6]
## Value Proposition
As a general User, I want to be able to search for of specific criteria so that the studio listings I am looking for, can fit my needs.
## Description
search-bar will be in the navigation header. Additional search-bar inputs will arise after clicking the input field.

All optional search-bar input's listed here:

- Number of Persons 
- Date range (for which time frame a studio is looked at)
- Services
- Submit
- Cancel
![Screenshot 2022-10-23 at 16 54 00](https://user-images.githubusercontent.com/68496958/197399113-dfd70f34-ee88-4f89-89d6-45285ba5a14e.png)

## Acception Criteria
- [x] The search parameters decide what will be shown in the search results
- [x] Click outside of calendar to close it // Click outside search filters to close it
## Tasks
- [x] create search-bar input
- [x] create search-bar option inputs: date-picker, number of persons, services
- [x] conditionally show search options when search input is active
- [x]on Submit send all values via router params to /search page 
- [x] Close Calendar/Search-filters with click outside its container
- [x] Add search and cancel button

**Comment by Ozanyurdakul98** [comment]
Thank you for your inputs. I've applied your suggestions and added further details
