### ISSUE TITLE
Make createListing Form functional

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#8]
## Value Proposition
As a Hoster, I want to be able to use the form with all its intended functionalities so that I can have somewhat of a user experience.
## Description
For example this editable times for the days should pop out if the user picks the option "Benutzerdefiniert.
For every of these functionalities states and onClick handlers are needed.
"<img width="242" alt="Screenshot 2022-10-17 at 11 56 12" src="https://user-images.githubusercontent.com/68496958/196148371-99f3e4d1-e655-4fb9-b2dc-d309dded76cc.png">

## Acception Criteria
- [ ] Form inputs should be functional as intended
## Tasks
- [ ] Form opening times functionality 
- [ ] Form studio type functionality
