### ISSUE TITLE
redesign Header search 

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#83]
## Value Proposition
As a < type of user >, I want < some goal > so that < some reason >.
## Description
make all filters (guests, date and  services) appear on one view.
make the studioservices in service-dropdown filter and Headerpage menu being dynmically fetched.
Add select radius options.
## Acception Criteria
- [ ] Actual functionality of feature
- [ ] listed here
- [ ] and another one
## Tasks
- [x] Move all Filter tabs to one view
- [x] make the Studioservices dropdown be dynamically fetched
- [x] add a select radius option
- [x] disable scrolling when filters shown
