### ISSUE TITLE
Radius & Sorting by distance

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#84]
## Description
Sorting by distance to searched address coordinates with Geolib function orderByDistance(point, arrayOfPoints).
Thus applied to the given radius of search-filter.
// Insert Wire Frame
## Acception Criteria
- [ ] Actual functionality of feature
- [ ] listed here
- [ ] and another one
## Tasks
- [x] radius functionality
- [x] sort by distance functionality
