### ISSUE TITLE
User profileText

### ISSUE THREAD

**Issue by Ozanyurdakul98** [Ozanyurdakul98/capstone-project#92]
## Value Proposition
Users have their own little "biography", here, defined as profileText. It will be displayed at the User`s profilepage and at the studioservice-detailpage on the user`s info-card.
## Description
// Insert Wire Frame
## Acception Criteria
- [ ] Actual functionality of feature
- [ ] listed here
- [ ] and another one
## Tasks
- [ ] add to user schema
- [ ]  add textarea formfield to editUserForm
- [ ] fetch profileText into UserDetailpage and into studioservices detailpage
